name: rest_one
description: Menu for restaurant
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dropdown_button2: ^2.1.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.1
  grock: ^0.2.9
  flutter_spinkit: ^5.2.0
  http: ^0.13.6
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  carousel_slider: ^4.2.1
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.1
  badges: ^3.1.1
  uuid: ^4.1.0
  iconsax: ^0.0.8
  get: ^4.5.0
  shimmer: ^2.0.0
  persistent_bottom_nav_bar: ^5.0.2
  cached_network_image: ^3.3.0

  flutter_native_splash: ^2.2.19
  easy_search_bar: ^2.5.0
  flutter_snake_navigationbar: ^0.6.1
  flutter_local_notifications: ^16.1.0
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  qr_flutter: ^4.0.0
  zoom_tap_animation: ^1.1.0

flutter_native_splash:
  #    color: "#ffffff"
  image: assets/images/splash/f.png
  background_image: assets/images/splash/b.jpg
  #    branding: assets/images/splash/f.png
  fullscreen: true
  android_12:
    image: assets/images/splash/f.png
    background_image: assets/images/splash/b.jpg
  android: true
  ios: true
  web: true


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^2.0.0
generate: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/AndikaB.ttf
    - family: Italic
      fonts:
        - asset: assets/fonts/AndikaBI.ttf
    - family: BoldI
      fonts:
        - asset: assets/fonts/AndikaI.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/AndikaR.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages